#!/bin/sh

# Set these paths appropriately

BIN=/Users/MikeDonald/Documents/TreeTagger/bin
CMD=/Users/MikeDonald/Documents/TreeTagger/cmd
LIB=/Users/MikeDonald/Documents/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
