#!/bin/sh

# Set these paths appropriately

BIN=/Users/MikeDonald/Documents/TreeTagger/bin
CMD=/Users/MikeDonald/Documents/TreeTagger/cmd
LIB=/Users/MikeDonald/Documents/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
