#!/bin/sh

# Set these paths appropriately

BIN=/Users/MikeDonald/Documents/TreeTagger/bin
CMD=/Users/MikeDonald/Documents/TreeTagger/cmd
LIB=/Users/MikeDonald/Documents/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
